##### Reference: https://graspingtech.com/wordpress-docker-compose/ ###
---
version: '3'

services:  ## Here we declare that we want to start the first service with traefik proxy version 2.3.6 ###
  my_traefik:  ## my_traefik is the service name###
    image: traefik:v2.3.6  ### Pulling traefik version 2.3.6 image ###
    restart: always
    command:
      - --accesslog
      - --api.insecure=true
      - --providers.docker
      - --providers.docker.exposedbydefault=false
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80
      - 443:443
      - 8080:8080

  my_wordpress:   ## Here we declare that we want to start the second service named my_wordpress using php7.4-apache###
    image: wordpress:php7.4-apache
    depends_on:
      - my_mysql
    restart: always
    environment:
      - WORDPRESS_DB_HOST=mysql
      - WORDPRESS_DB_USER=root
      - WORDPRESS_DB_NAME=wordpress
      - WORDPRESS_DB_PASSWORD=password
    expose:
      - 80
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wordpress.rule=Host('ingress.pixxelldesign.com`)"

  my_mysql:  ## Here we declare that we want to start the third service named my_mysql ###
    image: mysql:8.0.22
    restart: always
    environment:
      - MYSQL_DATABASE=wordpress
      - MYSQL_ROOT_PASSWORD=password

...